string(TOLOWER "${CMAKE_HOST_SYSTEM_PROCESSOR}" jt_host_processor)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE
    "${CMAKE_CURRENT_LIST_DIR}/../toolchains/gcc-16.cmake")

if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(VCPKG_TARGET_ARCHITECTURE x64)
    set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(VCPKG_ENV_PASSTHROUGH MSYS2_ROOT)
    set(VCPKG_ENV_PASSTHROUGH_UNTRACKED PATH)
    set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    if(jt_host_processor MATCHES "^(arm64|aarch64)$")
        set(VCPKG_TARGET_ARCHITECTURE arm64)
    else()
        set(VCPKG_TARGET_ARCHITECTURE x64)
    endif()
    set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
    set(VCPKG_LIBRARY_LINKAGE static)
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    if(jt_host_processor MATCHES "^(arm64|aarch64)$")
        set(VCPKG_TARGET_ARCHITECTURE arm64)
    else()
        set(VCPKG_TARGET_ARCHITECTURE x64)
    endif()
    set(VCPKG_CMAKE_SYSTEM_NAME Linux)
    set(VCPKG_LIBRARY_LINKAGE static)
else()
    message(FATAL_ERROR
        "The jt-gcc16 triplet supports macOS, Linux and Windows only")
endif()

set(VCPKG_CRT_LINKAGE dynamic)
